language: ruby
rvm:
- 2.2.3

install:
- "./alpha/bin/setup"

script:
- "./alpha/bin/travis"

after_success:
- "./alpha/bin/deploy"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  # flowdock: a3ab675b8495f55b53e6c3c6cf565d1e
  # email:
  #   - true@factsandfictions.net
