---
new_page_extension: html
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: static/./_pages
  label: Pages
  create: all
  match: "**/*"
upload_dir: static/media
public_path: static/media
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
