# CASIO ECR site, jekyll configuration file

# Important info for editors:
# ===========================
# - Settings related to content are stored in /_data/global.yml
# - Main navigation is stored in /_data/nav.yml
# - Content plages are stored at /…

# Custom vars
current_version:  1.0.0
repo:             https://bitbucket.org/casioecr/casio-ecr.es

# Where things are
plugins_dir:      ./_plugins
layouts_dir:      ./_layouts
data_dir:         ./_data
source:           .
destination:      ./_site

# Server
host:             127.0.0.1
port:             9003
encoding:         UTF-8
url:              'https://www.casio-ecr.es'
baseurl:          "" # does not include hostname
#detach:          false

# Gems var
plugins:
  - jekyll-assets
#  - jekyll-paginate

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Assets
sass:
  sass_dir: _assets/stylesheets

assets:
  compress:
    css: true
    js: true
  digest: true
  prefix: "/assets"
  sources:
    - _assets/bower
    - _assets/js
    - _assets/stylesheets
    - _assets/unify

# Handling Reading
# safe:             false

# Outputting
permalink:       /:title.html
#paginate_path:   /page:num
#paginate:        3
timezone:        'ES'
future:          future

# include:        [".htaccess,images"]
exclude:          [
  'node_modules'
  , '_assets/vendor'           # necessary for travis integration
  , 'bin'
  , 'sandbox'
  , 'unify'
  , '_glynn.yml'
  , 'package.json'
  , 'Gemfile'
  , 'Gemfile.lock'
  , 'Gruntfile.js'
  , 'bower.json'
  ]

include:        
  -  '.htaccess'
  -  'feed.xml' 
  -  'atom.xml' 
  -  'crossdomain.xml' 
  -  'sitemap.xml' 
  -  'humans.txt' 
  -  'robots.txt'
  -  'favicon.ico'
  -  'apple-touch-icon-precomposed.png'
  -  'google64c4ce35184cada9.html'
  -  'Acumbamail_bff03334-8ce0-11e7-b016-0050569a455d.html'
#  -  '_pages'
#  -  'unify'
  

# keep_files:     [".git", ".svn"]
markdown_ext:     'markdown,mkdown,mkdn,mkd,md'

# Collections
collections:
  pages:
    path:      pages
    output:    true
    permalink: /:title/


# Compress html
# @see: http://jch.penibelst.de/
compress_html:
  clippings: [div, p, ul, td, h1, h2, h3, h4, h5]
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# #minimagik
# mini_magick:
#     thumbnail:
#         source: media/images
#         destination: media/images/thumbnail
#         resize: "600x"