source "https://rubygems.org"
# Dependencies
# Fix build with travis on jekyll 3.4.3
gem 'jekyll', '3.4.3'
gem 'jekyll-watch', '1.4.0'
gem 'sprockets', '3.6.3'
gem 'sass'
# gem 'jekyll-paginate', '1.1.0'
# To compile sass + .js files while also using grunt
gem "jekyll-assets", '2.2.8'
# In case we use circle or travis to deploy we will need this
# à la 'kickster'
gem 'html-proofer'
# We can let the user upload the site with glynn
# They will need to clone the project and execute
# the bin/setup script on their machine and then
# set the credential values on _glynn.yml file
gem 'glynn', '1.2.3'

# and not used from kickster
# gem "jekyll-sitemap", "~> 0.10.0"

# Resize images
# gem 'jekyll-minimagick', '0.0.3'

# Site administration via jekyll-admin (https://github.com/jekyll/jekyll-admin)
# gem 'jekyll-menus', group: :jekyll_plugins