# P R O D U C T O S 
# ------------------
#
# Textos para la sección de promociones de producto que encabeza la homepage
#
# Ejemplo de formato para un copiar/pegar
#
# - title:        'Xxxx'
#   headline:     'Xxxxxx'
#   text:         > # this means to ignore newlines until next key
#     XXXXX.
#   button:       'Xxxx'
#   url:          'xxxx'
#   call:          'xxxx'   # optional
#   class:        'inverse'   # optional, aligns right
#   media:        'media/assets/products/sample-1900x1329.png'
#
# El campo 'url' ya no se usa
# El principal ahora es pdf_url


- title:        'Soluciones profesionales'
  headline:     '<strong>Soluciones</strong> Profesionales'
  text:         > # this means to ignore newlines until next key
    Equipos de punto de venta de gran fiabilidad y robustez, con un diseño moderno, elegante y funcional.
  media:        'media/assets/products/slide01-sample.jpg'
  pdf_url:      ''
  call:         ''
  button:       'Más información'
  pdf_guia_url: ''
  url:          '#contacto'

# - title:        'Soluciones de consumo'
#   headline:     'Soluciones de <strong>Consumo</strong>'
#   text:         > # this means to ignore newlines until next key
#     Cras tempus metus sit amet ipsum gravida, vitae euismod magna lacinia. Sed sit amet neque non dui pharetra porttitor.
#   media:        'media/assets/products/item-SE100.jpg'
#   pdf_url:      ''
#   call:         ''
#   button:       'Más información'
#   pdf_guia_url: ''
#   url:          '#contacto'

# # [√] V-R7000
# - title:        'Soluciones para sistemas'
#   headline:     '<strong>V-R7000/7100</strong> Solución inteligente y de diseño elegante'
#   text:         > # this means to ignore newlines until next key
#     Una nueva plataforma para la innovación en los comercios minoristas y la transformación de los puntos de venta.
#     <br><br>
#     Incluyen aplicaciones preinstaladas que van de la gestión de información de ventas o tiempo a funciones de análisis exhaustivo categorizables según el producto, departamento o grupo.
#   media:        'media/assets/products/item-VR7000.jpg'
#   pdf_url:      'media/pdf/Ficha_V-R7000.pdf'
#   button:       'Consultar especificaciones'
#   call:         'Compatible con el estándar de montaje VESA'
#   pdf_guia_url: ''
#   url:          'http://www.casio-europe.com/es/productos/sistemas-de-caja/soluciones-para-sistemas/#article-1'

# # [√] V-R200 blanca 2017 en restaurante chulo o tienda 
# - title:        'Terminales de red'
#   headline:     'La gama <strong>V-R200</strong> ofrece un nuevo estilo para tu punto de venta'
#   text:         > # this means to ignore newlines until next key
#     Una nueva plataforma para la innovación en los comercios minoristas y la transformación de los puntos de venta. 
#     <br><br>
#     Más que simples cajas registradoras, se trata de terminales de información que mejoran la gestión de los comercios.
#   pdf_url:      'media/pdf/Ficha_V-R200.pdf'
#   button:       'Consultar especificaciones'
#   media:        'media/assets/products/item-VR200.jpg'
#   call:         'Primera solución Android™ en el mercado'
#   url:          'http://www.casio-europe.com/es/productos/sistemas-de-caja/terminales-de-red/#article-1'
#   class:        ''
#   pdf_guia_url: ''

# # [√] IT-G400 comandero que no sembli que flota i amb la pantalla d'aplicació casio
# - title:        'Comanderos'
#   headline:     'La tablet profesional <strong>IT-G400</strong> es el <strong>comandero perfecto</strong>'
#   text:         > # this means to ignore newlines until next key
#     Ideal y versátil para todos los negocios. Comandero, TPV táctil, admisión de pedidos, gestión de venta al por menor… 
#     <br><br>
#     Cuenta con sistema operativo Android™, pueden aguantar una caída de un metro y cumplen con los estándares IP54 de resistencia al polvo y agua.
#   button:       'Consultar especificaciones'
#   call:         ''
#   url:          'https://www.casio-europe.com/es/productos/la-captura-movil-de-datos/it-g400/'
#   call:         'Ergonómicas y equipadas con protección anti-robo'
#   pdf_url:      'media/pdf/Ficha_IT-G400_EN.pdf'
#   pdf_guia_url: ''
#   media:        'media/assets/products/item-ITG400-b.jpg'

# # [√] SE-S400 amb fons de mosaic colorit de productes
# - title:        'Modelos SE-400+'
#   headline:     '<strong>Su registradora ideal</strong> para hostelería y comercio modernos <strong>SE-S400+</strong>'
#   text:         > # this means to ignore newlines until next key
#     Ya sea en un restaurante, bar o tienda: gracias a su diseño elegante, las nuevas cajas registradoras de la serie SE400+ encajan perfectamente en el entorno moderno de la hostelería y el comercio.
#     <br><br>
#     Rápida y silenciosa es perfecta para entornos tranquilos y hace que trabajar con la caja registradora sea una tarea agradable.
#   button:       'Consultar especificaciones'
#   url:          'http://www.casio-europe.com/es/productos/sistemas-de-caja/se-400-modelos/'
#   call:         'Diseño elegante y funciones innovadoras'
#   pdf_url:      'media/pdf/Ficha_SE-S400.pdf'
#   pdf_guia_url: 'media/pdf/Guia_rapida_SE-S400.pdf'
#   class:        ''
#   media:        'media/assets/products/item-SE400.jpg'

# # [√] SE-S100 dorada amb glow sobre restaurant xulo en blanc i negre
# - title:        'Cajas individuales'
#   headline:     '<strong>SE-S100</strong> Pon un toque de <strong>estilo</strong> a tu negocio'
#   text:         > # this means to ignore newlines until next key
#       Diseñada para una óptima operatividad, tiene teclado práctico y eficaz con el que, 
#       con un simple toque, accedes a las funciones más utilizadas. 
#       <br><br>
#       Incorpora una silenciosa impresora térmica de alto rendimiento y es compatible con tarjetas SD.
#   button:       'Consultar especificaciones'
#   call:         'La mejor manera de trabajar con factura simplificada'
#   url:          'http://www.casio-europe.com/es/productos/sistemas-de-caja/cajas-individuales/'
#   pdf_url:      'media/pdf/Ficha_SE-S100.pdf'
#   pdf_guia_url: 'media/pdf/Guia_rapida_SE-S100.pdf'
#   media:        'media/assets/products/item-SE100.jpg'

